### PR TITLE
Patch issue 5

### LINKED ISSUE #5: Testcontainer is not stopped, if class only contains @Disabled methods
# Description

When you have a test-class with only disabled test-methods, Testflight "forgets" to stop the corresponding container.

# Setup

If I have a class with only methods and that are annotated with `@Disabled`, the subsequent tests that use testflight fail, due to the container not being killed (see "The issue" for a log and my understanding of the problem).

## Example code

The following code fails:

```java
@MyQuarkusTest
class MyFirstListenerIT {

    @Test
    @Disabled // FIXME: remove, once implemented
    void testMyFirstListener() { }
}
```

On the other hand, I could fix this issue by putting the `@Disabled` on the class:

```java
@MyQuarkusTest
@Disabled // FIXME: remove, once implemented
class MyFirstListenerIT {

    @Test
    void testMyFirstListener() { }
}
```

A proper MWE might follow, if needed.

# The issue

My idea for the problem is, that if only a test-method is annotated with `@Disabled` and not the class, then Testflight does not notice, that this test was skipped. At the same time Testflight won't get a lifecycle callback that the test is finished and thus "forgets" to stop the container.
The workaround works, because when the test-class is disabled, then Testflight won't even start a container.

Also the bug *does not* occur, if there are other non-disabled test-methods.

Here's a log from our pipeline, where you can see two subsequent IT failing, due to not being able to assign the port. On my machine I could verify, that the container was still running.

```bash
[INFO] Running com.example.testflight.MyFirstListenerIT
2021-06-29 09:12:31,532 INFO  [🐳 [postgres:testflight-V1_0100]] (main) Creating container for image: postgres:testflight-V1_0100
2021-06-29 09:12:31,907 INFO  [🐳 [postgres:testflight-V1_0100]] (main) Starting container with ID: 342b63ee278cecc43f675b10713ffb6e2191825eb20c5e12f805f98fc1fc9504
2021-06-29 09:12:32,720 INFO  [🐳 [postgres:testflight-V1_0100]] (main) Container postgres:testflight-V1_0100 is starting: 342b63ee278cecc43f675b10713ffb6e2191825eb20c5e12f805f98fc1fc9504
2021-06-29 09:12:34,006 INFO  [🐳 [postgres:testflight-V1_0100]] (main) Container postgres:testflight-V1_0100 started in PT2.474243S

... Quarkus startup logs omitted...

[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 13.346 s - in com.example.testflight.MyFirstListenerIT
[INFO] Running com.example.testflight.MySecondListenerIT
2021-06-29 09:12:44,885 INFO  [🐳 [postgres:testflight-V1_0100]] (main) Creating container for image: postgres:testflight-V1_0100
2021-06-29 09:12:45,440 ERROR [🐳 [postgres:testflight-V1_0100]] (main) Could not start container: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint blissful_franklin (77f2b7496ca0b7f8231d30f6c1ca0057c1bda65a3b7c461c78ce63e7bdf50d12): Bind for 0.0.0.0:32770 failed: port is already allocated"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at space.testflight.FlywayExtension.initialize(FlywayExtension.java:212)
	at space.testflight.FlywayExtension.beforeAll(FlywayExtension.java:92)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

2021-06-29 09:12:45,453 ERROR [🐳 [postgres:testflight-V1_0100]] (main) There are no stdout/stderr logs available for the failed container
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.576 s <<< FAILURE! - in com.example.testflight.MySecondListenerIT
[ERROR] com.example.testflight.MySecondListenerIT  Time elapsed: 0.576 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: 
Status 500: {"message":"driver failed programming external connectivity on endpoint blissful_franklin (77f2b7496ca0b7f8231d30f6c1ca0057c1bda65a3b7c461c78ce63e7bdf50d12): Bind for 0.0.0.0:32770 failed: port is already allocated"}


[INFO] Running com.example.testflight.MyThirdListenerIT
2021-06-29 09:12:45,479 INFO  [🐳 [postgres:testflight-V1_0100]] (main) Creating container for image: postgres:testflight-V1_0100
2021-06-29 09:12:45,667 INFO  [🐳 [postgres:testflight-V1_0100]] (main) Starting container with ID: 11125ca83ff2f6014f76553f373cf4f3e5e8ce9ebbd06034e5e78cc89624b7b7
2021-06-29 09:12:45,977 ERROR [🐳 [postgres:testflight-V1_0100]] (main) Could not start container: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint crazy_kapitsa (7ee57d2f8e31c03091d4dd711a2cf159f0bde79b42a5fb11f1113d40cc81b312): Bind for 0.0.0.0:32770 failed: port is already allocated"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at space.testflight.FlywayExtension.initialize(FlywayExtension.java:212)
	at space.testflight.FlywayExtension.beforeAll(FlywayExtension.java:92)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

2021-06-29 09:12:45,979 ERROR [🐳 [postgres:testflight-V1_0100]] (main) There are no stdout/stderr logs available for the failed container
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.506 s <<< FAILURE! - in com.example.testflight.MyThirdListenerIT
[ERROR] com.example.testflight.MyThirdListenerIT  Time elapsed: 0.506 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: 
Status 500: {"message":"driver failed programming external connectivity on endpoint crazy_kapitsa (7ee57d2f8e31c03091d4dd711a2cf159f0bde79b42a5fb11f1113d40cc81b312): Bind for 0.0.0.0:32770 failed: port is already allocated"}
```

for reference our `MyQuarkusTest` annotation looks like this:
```java
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Stereotype
@ExtendWith({FlywayExtension.class, QuarkusTestExtension.class})
@Flyway(dockerImage = "postgres:12",
        databaseInstance = Flyway.DatabaseInstanceScope.PER_TEST_METHOD,
        configuration = {
                @ConfigProperty(key = "space.testflight.jdbc.url.property", value = "quarkus.datasource.jdbc.url"),
                @ConfigProperty(key = "space.testflight.jdbc.username.property", value = "quarkus.datasource.username"),
                @ConfigProperty(key = "space.testflight.jdbc.password.property", value = "quarkus.datasource.password"),
                @ConfigProperty(key = "flyway.locations", value = "filesystem:src/main/resources/db/migration")
        })
public @interface MyQuarkusTest {
}
```

### PR DESCRIPTION
**Pull request by JapuDCret**
# About
Resolves #5 by stopping the container, after a test-class was executed.

# Description
* bumped jacoco to `0.8.7`, so it supports JDK 17 and older (see [https://github.com/gradle/gradle/issues/15038](https://github.com/gradle/gradle/issues/15038))
* added `org.junit.platform:junit-platform-testkit` to be able to start the engine manually
* added `AbstractJupiterTestEngineTests.java` (based on [an internal junit5 class](https://github.com/junit-team/junit5/blob/main/junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/AbstractJupiterTestEngineTests.java))
* added `DisabledMethodsTest.java` to reproduce the issue

### CODE REVIEW

File: src/main/java/space/testflight/FlywayExtension.java [hunk 1]
```diff
@@ -127,6 +127,8 @@ public void afterAll(ExtensionContext context) throws Exception {
     if (getDatabaseInstance(context) == Flyway.DatabaseInstanceScope.PER_TEST_CLASS) {
```
Comment (ArneLimburg) [inline src/main/java/space/testflight/FlywayExtension.java:127]: Is this if statement required any more?

**Review by ArneLimburg — CHANGES_REQUESTED** [review]

File: src/main/java/space/testflight/FlywayExtension.java [hunk 2]
```diff
@@ -127,6 +127,8 @@ public void afterAll(ExtensionContext context) throws Exception {
...
       teardownDb(context, false);
     }
+
+    getGlobalStore(context).get(STORE_CONTAINER, AutoCloseable.class).close();
```
Comment (ArneLimburg) [inline src/main/java/space/testflight/FlywayExtension.java:131]: What does happen, if the container is already stopped?

File: src/main/java/space/testflight/FlywayExtension.java (hunk 1 above)
Comment (JapuDCret) [reply src/main/java/space/testflight/FlywayExtension.java:127]: Since I added a line for stopping the container in the global store, it might be necessary to close the container in the class store, if that's different. I think currently it's not, but it won't hurt for now (see response to your other remark).

File: src/main/java/space/testflight/FlywayExtension.java (hunk 2 above)
Comment (JapuDCret) [reply src/main/java/space/testflight/FlywayExtension.java:131]: Testcontainers checks if the container is running, before it tries to close and remove it.
Running this line multiple times, works also flawlessly.

See https://github.com/testcontainers/testcontainers-java/blob/testcontainers-1.1.5/core/src/main/java/org/testcontainers/utility/ResourceReaper.java#L92

**Review by ArneLimburg — APPROVED** [review]
